### ISSUE TITLE
US-33 Reservas: Acceder a historial

### ISSUE THREAD

**Issue by na7hk3r** [ProyectoIntegrador-DH-Equipo5/Frontend#75]
- [x] El usuario autenticado puede acceder a una sección específica en la que se muestran sus reservas anteriores.
- [x] Las reservas se muestran en una lista clara y ordenada por fecha o por otro criterio relevante para el
negocio.
- [x] Cada reserva incluye información relevante, como el nombre del producto reservado, la fecha de
reserva, la fecha de uso del producto, entre otros

**Comment by sBea88** [comment]
Se cumplen los criterios. Esta es la información del Historial de Reservas, como usuario en mi panel del perfil de usuario. Como se ve, el nombre de la obra (hasta ahora la que está subida online) es "la noche estrellada" no aparece.  Voy a crear una TK para revisión

Obra: Obra no encontrada
Fecha de Inicio: 8/12/2024
Fecha de Fin: 27/12/2024

Obra: Obra no encontrada
Fecha de Inicio: 11/1/2025
Fecha de Fin: 20/1/2025
