### ISSUE TITLE
TK-03: Políticas - Agregar acceso directo en tarjetas de productos

### ISSUE THREAD

**Issue by na7hk3r** [ProyectoIntegrador-DH-Equipo5/Frontend#80]
### **Acciones**:

- [x] Añadir un ícono o enlace en las tarjetas de productos.
- [x] Verificar que el bloque mantenga coherencia de diseño con el resto del sitio.

**Comment by sBea88** [comment]
Se cumple con los criterios. Cree otro TK relacionado a este, para resolver la navegación después de ingresar a las políticas: no una ayuda visual o botón intuitiva para volver a la reserva y continuar con el proceso

**Comment by na7hk3r** [comment]
Bea, este refiere a ver columnas con las politicas de la obra dentro del modal
